export interface TextPreset {
  text: string;
  fontSize: number;
  fontFamily: string;
  fill: string;
  stroke?: string;
  strokeWidth?: number;
  fontWeight: string;
  left: number;
  top: number;
  originX: "left" | "center" | "right";
  originY: "top" | "center" | "bottom";
  textAlign: "left" | "center" | "right";
  width: number;
}

export interface Template {
  id: string;
  name: string;
  platform: string;
  bgColor: string;
  bgGradient?: { from: string; to: string; angle: number };
  texts: TextPreset[];
}

export const YOUTUBE_TEMPLATES: Template[] = [
  {
    id: "yt-dark",
    name: "Dark Impact",
    platform: "youtube",
    bgColor: "#16213e",
    texts: [
      {
        text: "VIDEO TITLE",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#ffffff",
        stroke: "#ff0000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 300,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1100,
      },
      {
        text: "double-click to edit",
        fontSize: 52,
        fontFamily: "Arial",
        fill: "#cccccc",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "yt-bright",
    name: "Bright & Bold",
    platform: "youtube",
    bgColor: "#FFD700",
    texts: [
      {
        text: "Your Title Here",
        fontSize: 110,
        fontFamily: "Arial",
        fill: "#111111",
        fontWeight: "bold",
        left: 640,
        top: 280,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1100,
      },
      {
        text: "Channel name • Topic",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#333333",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "yt-minimal",
    name: "Clean Minimal",
    platform: "youtube",
    bgColor: "#1a1a2e",
    texts: [
      {
        text: "VIDEO TITLE",
        fontSize: 130,
        fontFamily: "Arial",
        fill: "#e94560",
        fontWeight: "bold",
        left: 640,
        top: 260,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1100,
      },
      {
        text: "your channel • topic",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
  {
    id: "yt-reaction",
    name: "Reaction Energy",
    platform: "youtube",
    bgColor: "#7c1a00",
    texts: [
      {
        text: "MY REACTION TO...",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#ff6600",
        stroke: "#ffffff",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 640,
        top: 260,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "this changed everything",
        fontSize: 52,
        fontFamily: "Arial",
        fill: "#ffcc99",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "yt-tutorial",
    name: "Tutorial Blue",
    platform: "youtube",
    bgColor: "#0d1b2a",
    texts: [
      {
        text: "HOW TO...",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#3b82f6",
        stroke: "#1e3a5f",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 640,
        top: 260,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "step by step guide for beginners",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#93c5fd",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
];

// ─── Instagram (1080×1080) ───────────────────────────────────────────────────
export const INSTAGRAM_TEMPLATES: Template[] = [
  {
    id: "ig-minimal",
    name: "Clean Minimal",
    platform: "instagram",
    bgColor: "#16213e",
    texts: [
      {
        text: "YOUR TITLE",
        fontSize: 110,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 540,
        top: 420,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 920,
      },
      {
        text: "subtitle text here",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#93c5fd",
        fontWeight: "normal",
        left: 540,
        top: 570,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 860,
      },
    ],
  },
  {
    id: "ig-vibrant",
    name: "Vibrant",
    platform: "instagram",
    bgColor: "#2563EB",
    texts: [
      {
        text: "YOUR MESSAGE",
        fontSize: 120,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 540,
        top: 440,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 960,
      },
      {
        text: "tap to edit subtitle",
        fontSize: 52,
        fontFamily: "Arial",
        fill: "#bfdbfe",
        fontWeight: "normal",
        left: 540,
        top: 600,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
  {
    id: "ig-dark",
    name: "Dark Mood",
    platform: "instagram",
    bgColor: "#0a0a0a",
    texts: [
      {
        text: "TITLE",
        fontSize: 140,
        fontFamily: "Impact",
        fill: "#FFD700",
        stroke: "#000000",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 540,
        top: 400,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 960,
      },
      {
        text: "your subtitle",
        fontSize: 52,
        fontFamily: "Arial",
        fill: "#cccccc",
        fontWeight: "normal",
        left: 540,
        top: 580,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 860,
      },
    ],
  },
  {
    id: "ig-orange",
    name: "Warm Orange",
    platform: "instagram",
    bgColor: "#7c2d12",
    texts: [
      {
        text: "YOUR STORY",
        fontSize: 120,
        fontFamily: "Impact",
        fill: "#fed7aa",
        stroke: "#7c2d12",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 540,
        top: 420,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 960,
      },
      {
        text: "tap to edit subtitle text",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fef3c7",
        fontWeight: "normal",
        left: 540,
        top: 590,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
  {
    id: "ig-navy",
    name: "Navy Bold",
    platform: "instagram",
    bgColor: "#0f172a",
    texts: [
      {
        text: "YOUR MESSAGE",
        fontSize: 116,
        fontFamily: "Arial",
        fill: "#38bdf8",
        fontWeight: "bold",
        left: 540,
        top: 420,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 960,
      },
      {
        text: "subtitle goes here",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e2e8f0",
        fontWeight: "normal",
        left: 540,
        top: 590,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
];

// ─── Facebook Cover (851×315) ────────────────────────────────────────────────
export const FACEBOOK_TEMPLATES: Template[] = [
  {
    id: "fb-professional",
    name: "Professional",
    platform: "facebook",
    bgColor: "#1e3a5f",
    texts: [
      {
        text: "YOUR PAGE NAME",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 425,
        top: 130,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 780,
      },
      {
        text: "Your tagline or description here",
        fontSize: 36,
        fontFamily: "Arial",
        fill: "#93c5fd",
        fontWeight: "normal",
        left: 425,
        top: 210,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 740,
      },
    ],
  },
  {
    id: "fb-bold",
    name: "Bold & Bright",
    platform: "facebook",
    bgColor: "#FFD700",
    texts: [
      {
        text: "PAGE TITLE",
        fontSize: 80,
        fontFamily: "Impact",
        fill: "#111827",
        fontWeight: "bold",
        left: 425,
        top: 130,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 780,
      },
      {
        text: "Your slogan goes here",
        fontSize: 38,
        fontFamily: "Arial",
        fill: "#374151",
        fontWeight: "normal",
        left: 425,
        top: 220,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 720,
      },
    ],
  },
  {
    id: "fb-minimal",
    name: "Clean Minimal",
    platform: "facebook",
    bgColor: "#f9fafb",
    texts: [
      {
        text: "Your Brand",
        fontSize: 76,
        fontFamily: "Arial",
        fill: "#111827",
        fontWeight: "bold",
        left: 425,
        top: 125,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 780,
      },
      {
        text: "tagline • website.com",
        fontSize: 36,
        fontFamily: "Arial",
        fill: "#6B7280",
        fontWeight: "normal",
        left: 425,
        top: 215,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 720,
      },
    ],
  },
  {
    id: "fb-dark",
    name: "Dark Pro",
    platform: "facebook",
    bgColor: "#111827",
    texts: [
      {
        text: "YOUR PAGE NAME",
        fontSize: 76,
        fontFamily: "Impact",
        fill: "#f9fafb",
        stroke: "#374151",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 425,
        top: 125,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 780,
      },
      {
        text: "your tagline here",
        fontSize: 36,
        fontFamily: "Arial",
        fill: "#9ca3af",
        fontWeight: "normal",
        left: 425,
        top: 215,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 720,
      },
    ],
  },
  {
    id: "fb-teal",
    name: "Teal Fresh",
    platform: "facebook",
    bgColor: "#0f3f3f",
    texts: [
      {
        text: "YOUR PAGE NAME",
        fontSize: 76,
        fontFamily: "Arial",
        fill: "#99f6e4",
        fontWeight: "bold",
        left: 425,
        top: 125,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 780,
      },
      {
        text: "tagline • your niche",
        fontSize: 36,
        fontFamily: "Arial",
        fill: "#ccfbf1",
        fontWeight: "normal",
        left: 425,
        top: 215,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 720,
      },
    ],
  },
];

// ─── Twitter/X Header (1500×500) ─────────────────────────────────────────────
export const TWITTER_TEMPLATES: Template[] = [
  {
    id: "tw-dark",
    name: "Dark Minimal",
    platform: "twitter",
    bgColor: "#0f172a",
    texts: [
      {
        text: "YOUR NAME / BRAND",
        fontSize: 96,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 750,
        top: 190,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
      {
        text: "your tagline or what you do",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#94a3b8",
        fontWeight: "normal",
        left: 750,
        top: 305,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1200,
      },
    ],
  },
  {
    id: "tw-purple",
    name: "Purple Gradient",
    platform: "twitter",
    bgColor: "#4c1d95",
    texts: [
      {
        text: "YOUR BRAND",
        fontSize: 110,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 750,
        top: 185,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
      {
        text: "building in public • creator • developer",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#ddd6fe",
        fontWeight: "normal",
        left: 750,
        top: 310,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1200,
      },
    ],
  },
  {
    id: "tw-light",
    name: "Clean Light",
    platform: "twitter",
    bgColor: "#f8fafc",
    texts: [
      {
        text: "Your Name",
        fontSize: 110,
        fontFamily: "Arial",
        fill: "#0f172a",
        fontWeight: "bold",
        left: 750,
        top: 185,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
      {
        text: "what you do • your niche • website.com",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#64748b",
        fontWeight: "normal",
        left: 750,
        top: 310,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1200,
      },
    ],
  },
  {
    id: "tw-teal",
    name: "Teal Creator",
    platform: "twitter",
    bgColor: "#0f3f3f",
    texts: [
      {
        text: "YOUR NAME / BRAND",
        fontSize: 100,
        fontFamily: "Arial",
        fill: "#99f6e4",
        fontWeight: "bold",
        left: 750,
        top: 185,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
      {
        text: "creator • builder • your niche",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ccfbf1",
        fontWeight: "normal",
        left: 750,
        top: 310,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1200,
      },
    ],
  },
  {
    id: "tw-orange",
    name: "Burnt Orange",
    platform: "twitter",
    bgColor: "#431407",
    texts: [
      {
        text: "YOUR BRAND NAME",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#fed7aa",
        stroke: "#7c2d12",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 750,
        top: 185,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
      {
        text: "your tagline • what you do",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fef3c7",
        fontWeight: "normal",
        left: 750,
        top: 310,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1200,
      },
    ],
  },
];

// ─── LinkedIn Banner (1584×396) ──────────────────────────────────────────────
export const LINKEDIN_TEMPLATES: Template[] = [
  {
    id: "li-navy",
    name: "Corporate Navy",
    platform: "linkedin",
    bgColor: "#0a2540",
    texts: [
      {
        text: "YOUR NAME / ROLE",
        fontSize: 90,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 792,
        top: 155,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1440,
      },
      {
        text: "Company • Specialization • Location",
        fontSize: 46,
        fontFamily: "Arial",
        fill: "#93c5fd",
        fontWeight: "normal",
        left: 792,
        top: 255,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
    ],
  },
  {
    id: "li-modern",
    name: "Modern Purple",
    platform: "linkedin",
    bgColor: "#581c87",
    texts: [
      {
        text: "YOUR NAME",
        fontSize: 100,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 792,
        top: 150,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1440,
      },
      {
        text: "Job Title • Company • Open to Opportunities",
        fontSize: 46,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 792,
        top: 255,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
    ],
  },
  {
    id: "li-minimal",
    name: "Clean Minimal",
    platform: "linkedin",
    bgColor: "#f1f5f9",
    texts: [
      {
        text: "Your Name",
        fontSize: 96,
        fontFamily: "Arial",
        fill: "#0f172a",
        fontWeight: "bold",
        left: 792,
        top: 148,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1440,
      },
      {
        text: "Role • Company • website.com",
        fontSize: 46,
        fontFamily: "Arial",
        fill: "#475569",
        fontWeight: "normal",
        left: 792,
        top: 255,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
    ],
  },
  {
    id: "li-green",
    name: "Emerald",
    platform: "linkedin",
    bgColor: "#064e3b",
    texts: [
      {
        text: "YOUR NAME / ROLE",
        fontSize: 92,
        fontFamily: "Arial",
        fill: "#6ee7b7",
        fontWeight: "bold",
        left: 792,
        top: 148,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1440,
      },
      {
        text: "Company • Specialization • Open to Work",
        fontSize: 46,
        fontFamily: "Arial",
        fill: "#d1fae5",
        fontWeight: "normal",
        left: 792,
        top: 255,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
    ],
  },
  {
    id: "li-dark",
    name: "Dark Professional",
    platform: "linkedin",
    bgColor: "#111827",
    texts: [
      {
        text: "YOUR NAME",
        fontSize: 100,
        fontFamily: "Arial",
        fill: "#f9fafb",
        fontWeight: "bold",
        left: 792,
        top: 148,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1440,
      },
      {
        text: "Job Title • Company • Location",
        fontSize: 46,
        fontFamily: "Arial",
        fill: "#9ca3af",
        fontWeight: "normal",
        left: 792,
        top: 255,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1360,
      },
    ],
  },
];

// ─── Gaming Thumbnail (1280×720) ─────────────────────────────────────────────
export const GAMING_TEMPLATES: Template[] = [
  {
    id: "gm-neon",
    name: "Neon Gaming",
    platform: "gaming",
    bgColor: "#16213e",
    texts: [
      {
        text: "GAME TITLE",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#00ff88",
        stroke: "#00aa55",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "epic gameplay • world record",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#00ccff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "gm-fire",
    name: "Fire Red",
    platform: "gaming",
    bgColor: "#0d0000",
    texts: [
      {
        text: "YOUR TITLE HERE",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#ff4400",
        stroke: "#ff0000",
        strokeWidth: 4,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "click to edit subtitle",
        fontSize: 52,
        fontFamily: "Arial",
        fill: "#ffaa00",
        fontWeight: "bold",
        left: 640,
        top: 425,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "gm-cyber",
    name: "Cyberpunk",
    platform: "gaming",
    bgColor: "#0d001a",
    texts: [
      {
        text: "THUMBNAIL TITLE",
        fontSize: 96,
        fontFamily: "Arial",
        fill: "#f0e040",
        stroke: "#ff00ff",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 265,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "level up • season 5 • insane plays",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#cc88ff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "gm-purple",
    name: "Purple Throne",
    platform: "gaming",
    bgColor: "#1a0030",
    texts: [
      {
        text: "EPIC GAMEPLAY",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#c084fc",
        stroke: "#6b21a8",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "new season • ranked • highlights",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "gm-ice",
    name: "Arctic Ice",
    platform: "gaming",
    bgColor: "#001428",
    texts: [
      {
        text: "FROZEN WIN",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#bae6fd",
        stroke: "#0369a1",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "chill • clutch • cold blooded",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e0f2fe",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Minecraft Thumbnail (1280×720) ──────────────────────────────────────────
export const MINECRAFT_TEMPLATES: Template[] = [
  {
    id: "mc-grass",
    name: "Grass Block",
    platform: "minecraft",
    bgColor: "#1a3d00",
    texts: [
      {
        text: "VIDEO TITLE",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#ffffff",
        stroke: "#2d7d00",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "Minecraft Survival • Episode 1",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#7fff00",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "mc-diamond",
    name: "Diamond Mine",
    platform: "minecraft",
    bgColor: "#050f1a",
    texts: [
      {
        text: "FOUND DIAMONDS!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#5bc8f5",
        stroke: "#1a3a5c",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "Mining • Survival • Season 1",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#a0d8ef",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "mc-nether",
    name: "Nether Portal",
    platform: "minecraft",
    bgColor: "#1a0010",
    texts: [
      {
        text: "THE NETHER",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#ff6600",
        stroke: "#cc0000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "survival challenge • hardcore mode",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ff9966",
        fontWeight: "bold",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "mc-sky",
    name: "Sky Limit",
    platform: "minecraft",
    bgColor: "#1a6ebd",
    texts: [
      {
        text: "SKY BLOCK",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#ffffff",
        stroke: "#1e40af",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "floating islands • custom world",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#dbeafe",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "mc-end",
    name: "End Dimension",
    platform: "minecraft",
    bgColor: "#0d0d1a",
    texts: [
      {
        text: "THE END",
        fontSize: 120,
        fontFamily: "Impact",
        fill: "#a855f7",
        stroke: "#3b0764",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "ender dragon • end cities • elytra",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Roblox Thumbnail (1280×720) ─────────────────────────────────────────────
export const ROBLOX_TEMPLATES: Template[] = [
  {
    id: "rb-red",
    name: "Roblox Red",
    platform: "roblox",
    bgColor: "#1a0000",
    texts: [
      {
        text: "ROBLOX VIDEO",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#ff3333",
        stroke: "#ffffff",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "obby • adopt me • blox fruits",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "rb-neon",
    name: "Neon Obby",
    platform: "roblox",
    bgColor: "#050d1a",
    texts: [
      {
        text: "I BEAT THE OBBY!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#00ff99",
        stroke: "#004433",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "hardest obby • level 100 • tips",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#7fffd4",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "rb-gold",
    name: "Rare Item",
    platform: "roblox",
    bgColor: "#0f0a00",
    texts: [
      {
        text: "GOT A RARE ITEM!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#ffd700",
        stroke: "#7a5c00",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "limited • pet sim • trade",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffe066",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "rb-blue",
    name: "Blox Fruits",
    platform: "roblox",
    bgColor: "#001040",
    texts: [
      {
        text: "BLOX FRUITS",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#fbbf24",
        stroke: "#7c4500",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "legendary fruit • max level • pvp",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#93c5fd",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "rb-pink",
    name: "Adopt Me",
    platform: "roblox",
    bgColor: "#1a0028",
    texts: [
      {
        text: "ADOPT ME PETS!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#f9a8d4",
        stroke: "#831843",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "new pets • ultra rare • trading",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fce7f3",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Blox Fruits Thumbnail (1280×720) ────────────────────────────────────────
export const BLOX_FRUITS_TEMPLATES: Template[] = [
  {
    id: "bf-legendary",
    name: "Legendary Fruit",
    platform: "blox_fruits",
    bgColor: "#001040",
    texts: [
      {
        text: "LEGENDARY FRUIT!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#fbbf24",
        stroke: "#7c4500",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "blox fruits • rare drop • showcase",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#93c5fd",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "bf-raid",
    name: "Raid Boss",
    platform: "blox_fruits",
    bgColor: "#1a0000",
    texts: [
      {
        text: "RAID BOSS FIGHT!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#f97316",
        stroke: "#7f1d1d",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "boss raid • max level • pvp",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fca5a5",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "bf-mythical",
    name: "Mythical Power",
    platform: "blox_fruits",
    bgColor: "#0f0020",
    texts: [
      {
        text: "MYTHICAL POWER!",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#c084fc",
        stroke: "#4c1d95",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "awakening • devil fruit • op combo",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "bf-sea",
    name: "Sea King",
    platform: "blox_fruits",
    bgColor: "#001a1a",
    texts: [
      {
        text: "SEA KING SLAYER",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#22d3ee",
        stroke: "#164e63",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "third sea • boss kill • exploration",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#a5f3fc",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Fortnite Thumbnail (1280×720) ───────────────────────────────────────────
export const FORTNITE_TEMPLATES: Template[] = [
  {
    id: "fn-storm",
    name: "Storm Eye",
    platform: "fortnite",
    bgColor: "#0a0520",
    texts: [
      {
        text: "VICTORY ROYALE",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#f5e642",
        stroke: "#7700ff",
        strokeWidth: 4,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "solo • no builds • chapter 5",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#c084fc",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "fn-zero",
    name: "Zero Point",
    platform: "fortnite",
    bgColor: "#000d1a",
    texts: [
      {
        text: "INSANE WIN",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#00d4ff",
        stroke: "#004466",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "20 kill game • ranked • tips",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#7dd3fc",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "fn-gold",
    name: "Legendary Loot",
    platform: "fortnite",
    bgColor: "#1a0d00",
    texts: [
      {
        text: "LEGENDARY LOADOUT",
        fontSize: 88,
        fontFamily: "Impact",
        fill: "#fbbf24",
        stroke: "#92400e",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 265,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "best weapons • chapter 5 meta",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fde68a",
        fontWeight: "normal",
        left: 640,
        top: 425,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "fn-pink",
    name: "Battle Royale Pink",
    platform: "fortnite",
    bgColor: "#2d0020",
    texts: [
      {
        text: "BATTLE ROYALE",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#f472b6",
        stroke: "#831843",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "squad wipe • no builds • season 5",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fce7f3",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "fn-green",
    name: "Jungle Assault",
    platform: "fortnite",
    bgColor: "#001a08",
    texts: [
      {
        text: "JUNGLE VICTORY",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#4ade80",
        stroke: "#14532d",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "stealth • assault • chapter 5",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#bbf7d0",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── YouTube Banner / Channel Art (2560×1440) ─────────────────────────────────
export const YOUTUBE_BANNER_TEMPLATES: Template[] = [
  {
    id: "yb-dark",
    name: "Dark Channel",
    platform: "youtube_banner",
    bgColor: "#0a0a0a",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 200,
        fontFamily: "Impact",
        fill: "#ffffff",
        stroke: "#ff0000",
        strokeWidth: 4,
        fontWeight: "bold",
        left: 1280,
        top: 580,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2300,
      },
      {
        text: "New videos every week • Subscribe now",
        fontSize: 88,
        fontFamily: "Arial",
        fill: "#cccccc",
        fontWeight: "normal",
        left: 1280,
        top: 820,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2100,
      },
    ],
  },
  {
    id: "yb-minimal",
    name: "Clean Minimal",
    platform: "youtube_banner",
    bgColor: "#ffffff",
    texts: [
      {
        text: "Your Channel Name",
        fontSize: 210,
        fontFamily: "Arial",
        fill: "#111111",
        fontWeight: "bold",
        left: 1280,
        top: 570,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2300,
      },
      {
        text: "your niche • upload schedule • tagline",
        fontSize: 88,
        fontFamily: "Arial",
        fill: "#555555",
        fontWeight: "normal",
        left: 1280,
        top: 820,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2100,
      },
    ],
  },
  {
    id: "yb-gaming",
    name: "Gaming Channel",
    platform: "youtube_banner",
    bgColor: "#050510",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 200,
        fontFamily: "Impact",
        fill: "#00ff88",
        stroke: "#006633",
        strokeWidth: 4,
        fontWeight: "bold",
        left: 1280,
        top: 565,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2300,
      },
      {
        text: "Gaming • Tutorials • Highlights",
        fontSize: 92,
        fontFamily: "Arial",
        fill: "#00ccff",
        fontWeight: "bold",
        left: 1280,
        top: 820,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2100,
      },
    ],
  },
  {
    id: "yb-purple",
    name: "Neon Purple",
    platform: "youtube_banner",
    bgColor: "#1a0030",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 200,
        fontFamily: "Impact",
        fill: "#c084fc",
        stroke: "#6b21a8",
        strokeWidth: 4,
        fontWeight: "bold",
        left: 1280,
        top: 565,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2300,
      },
      {
        text: "Videos every week • Subscribe now",
        fontSize: 92,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 1280,
        top: 820,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2100,
      },
    ],
  },
  {
    id: "yb-red",
    name: "Crimson Impact",
    platform: "youtube_banner",
    bgColor: "#1a0000",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 200,
        fontFamily: "Impact",
        fill: "#ff3333",
        stroke: "#7f0000",
        strokeWidth: 4,
        fontWeight: "bold",
        left: 1280,
        top: 565,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2300,
      },
      {
        text: "New videos every week • Subscribe",
        fontSize: 92,
        fontFamily: "Arial",
        fill: "#fecaca",
        fontWeight: "normal",
        left: 1280,
        top: 820,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 2100,
      },
    ],
  },
];

// ─── OG Image (1200×630) ─────────────────────────────────────────────────────
export const OG_TEMPLATES: Template[] = [
  {
    id: "og-blog",
    name: "Blog Post",
    platform: "og",
    bgColor: "#ffffff",
    texts: [
      {
        text: "Your Blog Post Title Goes Here",
        fontSize: 80,
        fontFamily: "Arial",
        fill: "#111827",
        fontWeight: "bold",
        left: 600,
        top: 240,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1080,
      },
      {
        text: "yoursite.com",
        fontSize: 44,
        fontFamily: "Arial",
        fill: "#6B7280",
        fontWeight: "normal",
        left: 600,
        top: 390,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "og-dark",
    name: "Dark Tech",
    platform: "og",
    bgColor: "#0f172a",
    texts: [
      {
        text: "Article or Product Title",
        fontSize: 84,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 600,
        top: 235,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1080,
      },
      {
        text: "yoursite.com • category",
        fontSize: 44,
        fontFamily: "Arial",
        fill: "#94a3b8",
        fontWeight: "normal",
        left: 600,
        top: 385,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "og-brand",
    name: "Branded",
    platform: "og",
    bgColor: "#7C3AED",
    texts: [
      {
        text: "Your Page Title",
        fontSize: 90,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 600,
        top: 230,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1080,
      },
      {
        text: "yoursite.com",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#ddd6fe",
        fontWeight: "normal",
        left: 600,
        top: 385,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "og-green",
    name: "Dark Green",
    platform: "og",
    bgColor: "#052e16",
    texts: [
      {
        text: "Your Page Title Here",
        fontSize: 84,
        fontFamily: "Arial",
        fill: "#4ade80",
        fontWeight: "bold",
        left: 600,
        top: 235,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1080,
      },
      {
        text: "yoursite.com • category",
        fontSize: 44,
        fontFamily: "Arial",
        fill: "#bbf7d0",
        fontWeight: "normal",
        left: 600,
        top: 385,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
  {
    id: "og-orange",
    name: "Warm Rust",
    platform: "og",
    bgColor: "#431407",
    texts: [
      {
        text: "Your Page Title Here",
        fontSize: 84,
        fontFamily: "Arial",
        fill: "#fed7aa",
        fontWeight: "bold",
        left: 600,
        top: 235,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1080,
      },
      {
        text: "yoursite.com • category",
        fontSize: 44,
        fontFamily: "Arial",
        fill: "#fef3c7",
        fontWeight: "normal",
        left: 600,
        top: 385,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1000,
      },
    ],
  },
];

// ─── Among Us Thumbnail (1280×720) ───────────────────────────────────────────
export const AMONG_US_TEMPLATES: Template[] = [
  {
    id: "au-impostor",
    name: "Impostor Red",
    platform: "among_us",
    bgColor: "#0d0005",
    texts: [
      {
        text: "IMPOSTOR DETECTED",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#ff2727",
        stroke: "#000000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "sus • vent • kill • crew",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#ffb3b3",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "au-crewmate",
    name: "Crewmate Blue",
    platform: "among_us",
    bgColor: "#001430",
    texts: [
      {
        text: "CREWMATE WIN!",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#4fffde",
        stroke: "#003333",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "task complete • all vents clear",
        fontSize: 48,
        fontFamily: "Arial",
        fill: "#b3ffee",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "au-emergency",
    name: "Emergency Meeting",
    platform: "among_us",
    bgColor: "#1a0a00",
    texts: [
      {
        text: "EMERGENCY MEETING!",
        fontSize: 86,
        fontFamily: "Impact",
        fill: "#ffe600",
        stroke: "#7a3f00",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "who is the impostor?",
        fontSize: 52,
        fontFamily: "Arial",
        fill: "#fff0b3",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Apex Legends Thumbnail (1280×720) ───────────────────────────────────────
export const APEX_LEGENDS_TEMPLATES: Template[] = [
  {
    id: "ap-champion",
    name: "Champion Orange",
    platform: "apex_legends",
    bgColor: "#0a0300",
    texts: [
      {
        text: "CHAMPION!",
        fontSize: 120,
        fontFamily: "Impact",
        fill: "#ff8c00",
        stroke: "#4a1800",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "apex legends • squad wipe",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffd6a0",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "ap-legend",
    name: "Legend Gold",
    platform: "apex_legends",
    bgColor: "#080600",
    texts: [
      {
        text: "APEX PREDATOR",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#ffd700",
        stroke: "#5a3500",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "ranked • kill leader • 20 bomb",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fff0a0",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "ap-dark",
    name: "Dark Red",
    platform: "apex_legends",
    bgColor: "#050000",
    texts: [
      {
        text: "20 BOMB GAME!",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#ff3333",
        stroke: "#6b0000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "bloodhound • wraith • octane",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffb3b3",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Call of Duty Thumbnail (1280×720) ───────────────────────────────────────
export const COD_TEMPLATES: Template[] = [
  {
    id: "cod-military",
    name: "Military Dark",
    platform: "cod",
    bgColor: "#0d1117",
    texts: [
      {
        text: "NUKE GAME!",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#ffffff",
        stroke: "#00ff41",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "call of duty • warzone • mw3",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#a0a0a0",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "cod-orange",
    name: "Combat Orange",
    platform: "cod",
    bgColor: "#0a0600",
    texts: [
      {
        text: "30 KILL GAME",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#ff6600",
        stroke: "#7f2000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "warzone • ranked • highlights",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffb380",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "cod-camo",
    name: "Camo Green",
    platform: "cod",
    bgColor: "#1a2410",
    texts: [
      {
        text: "BEST LOADOUT",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#d4e84a",
        stroke: "#3d5a00",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "class setup • tips • season",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#c5d9a0",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── GTA Thumbnail (1280×720) ─────────────────────────────────────────────────
export const GTA_TEMPLATES: Template[] = [
  {
    id: "gta-gold",
    name: "GTA Gold",
    platform: "gta",
    bgColor: "#0a0800",
    texts: [
      {
        text: "GTA ONLINE",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#ffd700",
        stroke: "#7a5c00",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "heist • money • new update",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffe566",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "gta-purple",
    name: "Night Purple",
    platform: "gta",
    bgColor: "#08001a",
    texts: [
      {
        text: "$10M HEIST!",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#c084fc",
        stroke: "#4c1d95",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "gta 5 • gta online • money grind",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "gta-red",
    name: "Wanted Red",
    platform: "gta",
    bgColor: "#0d0000",
    texts: [
      {
        text: "5 STAR WANTED",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#ff2222",
        stroke: "#7f0000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "gta 5 • chaos • funny moments",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffaaaa",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── CS2 Thumbnail (1280×720) ─────────────────────────────────────────────────
export const CS2_TEMPLATES: Template[] = [
  {
    id: "cs2-blue",
    name: "CT Blue",
    platform: "cs2",
    bgColor: "#000d1f",
    texts: [
      {
        text: "1 vs 5 CLUTCH",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#4da6ff",
        stroke: "#003d80",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "cs2 • global elite • ranked",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#99ccff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "cs2-orange",
    name: "T-Side Orange",
    platform: "cs2",
    bgColor: "#120800",
    texts: [
      {
        text: "ACE ROUND!",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#ff8c00",
        stroke: "#7f3800",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "cs2 • faceit • premier mode",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffcc80",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "cs2-minimal",
    name: "Pro Minimal",
    platform: "cs2",
    bgColor: "#0a0a0a",
    texts: [
      {
        text: "CS2 HIGHLIGHTS",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#ffffff",
        stroke: "#555555",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "tips • tricks • best plays",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#aaaaaa",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── PUBG Thumbnail (1280×720) ────────────────────────────────────────────────
export const PUBG_TEMPLATES: Template[] = [
  {
    id: "pubg-orange",
    name: "Chicken Dinner",
    platform: "pubg",
    bgColor: "#0d0800",
    texts: [
      {
        text: "#1 WINNER!",
        fontSize: 110,
        fontFamily: "Impact",
        fill: "#f59e0b",
        stroke: "#78350f",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "pubg • chicken dinner • solo",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fde68a",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "pubg-military",
    name: "Military Tan",
    platform: "pubg",
    bgColor: "#1a1208",
    texts: [
      {
        text: "20 KILLS GAME",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#d4b483",
        stroke: "#5a3e0a",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "pubg mobile • squad • ranked",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#e8d5b0",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "pubg-dark",
    name: "Night Drop",
    platform: "pubg",
    bgColor: "#050a12",
    texts: [
      {
        text: "SOLO SQUAD WIN",
        fontSize: 96,
        fontFamily: "Impact",
        fill: "#22d3ee",
        stroke: "#0e4f5c",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "pubg • erangel • miramar",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#a5f3fc",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── Valorant Thumbnail (1280×720) ───────────────────────────────────────────
export const VALORANT_TEMPLATES: Template[] = [
  {
    id: "vl-impact",
    name: "Agent Impact",
    platform: "valorant",
    bgColor: "#0d0000",
    texts: [
      {
        text: "VALORANT CLIP",
        fontSize: 108,
        fontFamily: "Impact",
        fill: "#ff4655",
        stroke: "#7f0000",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "ace • clutch • highlights",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "vl-ace",
    name: "ACE Gold",
    platform: "valorant",
    bgColor: "#0a0800",
    texts: [
      {
        text: "ACE ROUND!",
        fontSize: 120,
        fontFamily: "Impact",
        fill: "#fbbf24",
        stroke: "#78350f",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "5k • radiant • ranked game",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#fde68a",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
  {
    id: "vl-clutch",
    name: "Clutch Navy",
    platform: "valorant",
    bgColor: "#000d1a",
    texts: [
      {
        text: "1 vs 5 CLUTCH",
        fontSize: 100,
        fontFamily: "Impact",
        fill: "#38bdf8",
        stroke: "#0369a1",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 640,
        top: 270,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1150,
      },
      {
        text: "unrated • ranked • best plays",
        fontSize: 50,
        fontFamily: "Arial",
        fill: "#bae6fd",
        fontWeight: "normal",
        left: 640,
        top: 430,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1050,
      },
    ],
  },
];

// ─── TikTok Cover (1080×1920 portrait) ──────────────────────────────────────
export const TIKTOK_TEMPLATES: Template[] = [
  {
    id: "tt-viral",
    name: "Viral Pink",
    platform: "tiktok",
    bgColor: "#16213e",
    texts: [
      {
        text: "WATCH THIS!",
        fontSize: 140,
        fontFamily: "Impact",
        fill: "#FF0050",
        stroke: "#7f0028",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 540,
        top: 600,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 950,
      },
      {
        text: "double-click to edit",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "normal",
        left: 540,
        top: 800,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
  {
    id: "tt-cyan",
    name: "Dark Glow",
    platform: "tiktok",
    bgColor: "#0a0a0a",
    texts: [
      {
        text: "TRENDING NOW",
        fontSize: 130,
        fontFamily: "Impact",
        fill: "#00f2ea",
        stroke: "#005f5c",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 540,
        top: 600,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 950,
      },
      {
        text: "double-click to edit",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#ccfffe",
        fontWeight: "normal",
        left: 540,
        top: 800,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
  {
    id: "tt-yellow",
    name: "Trending Yellow",
    platform: "tiktok",
    bgColor: "#1a0028",
    texts: [
      {
        text: "MUST SEE!",
        fontSize: 150,
        fontFamily: "Impact",
        fill: "#ffe600",
        stroke: "#7a5c00",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 540,
        top: 600,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 950,
      },
      {
        text: "double-click to edit",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#FF0050",
        fontWeight: "normal",
        left: 540,
        top: 800,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 900,
      },
    ],
  },
];

// ─── Twitch Banner / Offline Screen (1920×1080) ───────────────────────────────
export const TWITCH_TEMPLATES: Template[] = [
  {
    id: "tw-purple",
    name: "Twitch Purple",
    platform: "twitch",
    bgColor: "#1a0533",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 140,
        fontFamily: "Impact",
        fill: "#bf94ff",
        stroke: "#6441a5",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 960,
        top: 420,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1700,
      },
      {
        text: "OFFLINE — Back soon!",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#e9d5ff",
        fontWeight: "normal",
        left: 960,
        top: 590,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1500,
      },
    ],
  },
  {
    id: "tw-neon",
    name: "Neon Gaming",
    platform: "twitch",
    bgColor: "#0a0a0a",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 150,
        fontFamily: "Impact",
        fill: "#00ff88",
        stroke: "#006633",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 960,
        top: 400,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1700,
      },
      {
        text: "OFFLINE • Stream starts soon",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#00ccff",
        fontWeight: "normal",
        left: 960,
        top: 580,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1500,
      },
    ],
  },
  {
    id: "tw-dark",
    name: "Minimal Dark",
    platform: "twitch",
    bgColor: "#0f172a",
    texts: [
      {
        text: "Channel Name",
        fontSize: 130,
        fontFamily: "Arial",
        fill: "#ffffff",
        fontWeight: "bold",
        left: 960,
        top: 420,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1700,
      },
      {
        text: "Offline — see you next stream",
        fontSize: 68,
        fontFamily: "Arial",
        fill: "#94a3b8",
        fontWeight: "normal",
        left: 960,
        top: 585,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1500,
      },
    ],
  },
  {
    id: "tw-fire",
    name: "Fire Red",
    platform: "twitch",
    bgColor: "#1c0506",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 150,
        fontFamily: "Impact",
        fill: "#ff4500",
        stroke: "#7f1d1d",
        strokeWidth: 3,
        fontWeight: "bold",
        left: 960,
        top: 400,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1700,
      },
      {
        text: "OFFLINE • Coming back soon",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#fed7aa",
        fontWeight: "normal",
        left: 960,
        top: 580,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1500,
      },
    ],
  },
  {
    id: "tw-blue",
    name: "Ice Blue",
    platform: "twitch",
    bgColor: "#0c1a2e",
    texts: [
      {
        text: "CHANNEL NAME",
        fontSize: 140,
        fontFamily: "Impact",
        fill: "#38bdf8",
        stroke: "#0c4a6e",
        strokeWidth: 2,
        fontWeight: "bold",
        left: 960,
        top: 420,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1700,
      },
      {
        text: "BRB • Stream returns soon",
        fontSize: 72,
        fontFamily: "Arial",
        fill: "#bae6fd",
        fontWeight: "normal",
        left: 960,
        top: 590,
        originX: "center",
        originY: "center",
        textAlign: "center",
        width: 1500,
      },
    ],
  },
];
